export const CURRENT_LOCALE = 'CURRENT_LOCALE';
export const CURRENT_USER = 'CURRENT_USER';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
